name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -y asciidoctor && sudo apt-get install -y linkchecker
      - run: make main.html && linkchecker --check-extern ./main.html >> rapport_linkchecker.txt
      - name: Uploading result in artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test result
          path: rapport_linkchecker.txt
        
          